name: 'uSync.CLI-action Info'
description:
  'A Github action wrapper for https://github.com/Jumoo/uSync.CommandLine'
author: 'mattou07'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  command:
    description:
      'The command you would like to run from the uSync CLI (Defaults to info
      command)'
    required: false
    default: 'info'

  server:
    description: 'URL to for the Umbraco website to target'
    required: true

  key:
    description: 'HMAC Key for authentication'
    required: true

# Define your outputs here.
outputs:
  version:
    description: 'Version of uSync CLI installed.'

runs:
  using: node20
  main: ../dist/invoke/index.js
