name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  # test-typescript:
  #   name: TypeScript Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       id: setup-node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version-file: .node-version
  #         cache: npm

  #     - name: Install Dependencies
  #       id: npm-ci
  #       run: npm ci

  #     - name: Check Format
  #       id: npm-format-check
  #       run: npm run format:check

  #     - name: Lint
  #       id: npm-lint
  #       run: npm run lint

  #     - name: Test
  #       id: npm-ci-test
  #       run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Setup Action
        id: setup-action
        uses: ./setup

      - name: Test Invoke Action (default)
        id: invoke-action-default
        uses: ./invoke
        with:
          server: ${{ secrets.TARGETURL}}
          key: ${{ secrets.HMAC }}

      - name: Test Invoke Action (ping)
        id: invoke-action-ping
        uses: ./invoke
        with:
          command: 'ping'
          server: ${{ secrets.TARGETURL}}
          key: ${{ secrets.HMAC }}

      - name: Test Invoke Action (Rebuild DB Cache)
        id: invoke-action-rebuildDBCache
        uses: ./invoke
        with:
          command: 'Rebuild-DBCache'
          server: ${{ secrets.TARGETURL}}
          key: ${{ secrets.HMAC }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.version }}"
